services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bmw-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./lessons_learned.db
      - DEBUG=true
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=10485760
      - ALLOWED_FILE_TYPES=image/jpeg,image/png,application/pdf
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app
      - ./backend/rag:/app/rag
    networks:
      - bmw-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bmw-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bmw-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  bmw-network:
    driver: bridge

volumes:
  backend-uploads:
  backend-db:
  backend-chroma: